### PR TITLE
feat(modelService): add support for switching backends

### LINKED ISSUE #98: A util code to detect if user's environment support webgpu or not in simulator and model

### LINKED ISSUE #108: auto choose runtime provider's backend

### PR DESCRIPTION
**Pull request by Lutra-Fs**
- add support for switching backends
- use WebGPU when available

Close #98 
Close #108

### CODE REVIEW

**Review by peipacut — CHANGES_REQUESTED** [review]
I just realised that when you remove the `initSubs` observer in #116, you also removed automatically issuing `start` to the model on initialisation which means the user has to manually press play everytime to start the model. https://github.com/techlauncher-mlai-edge-physics/CFlowSim/pull/116/commits/2469c5695cd66077395db0eff8bbaf7c4fc67a21#diff-7eed7666d6e0a7a95b5164cc3c2e00d1d98811cd7d2af488a56069bd674863bfL125-L129

I'll continue to block this PR until the model can issue start to itself again. I propose we go back to using the `initSubs` observer so the simulator can start the model on model initialisation, but I'm open to other ways of doing this.

Another point I'll make is that with this PR, the WebGPU backend no longer works on my machine under the beta version of chrome. ie. the screen goes blank and I get errors about creating a WebGL context. We can ignore this issue for this PR and investigate it later.

**Comment by Lutra-Fs** [comment]
> I just realised that when you remove the `initSubs` observer in #116, you also removed automatically issuing `start` to the model on initialisation which means the user has to manually press play everytime to start the model. [2469c56#diff-7eed7666d6e0a7a95b5164cc3c2e00d1d98811cd7d2af488a56069bd674863bfL125-L129](https://github.com/techlauncher-mlai-edge-physics/CFlowSim/commit/2469c5695cd66077395db0eff8bbaf7c4fc67a21#diff-7eed7666d6e0a7a95b5164cc3c2e00d1d98811cd7d2af488a56069bd674863bfL125-L129)
> 
> I'll continue to block this PR until the model can issue start to itself again. I propose we go back to using the `initSubs` observer so the simulator can start the model on model initialisation, but I'm open to other ways of doing this.
> 
> Another point I'll make is that with this PR, the WebGPU backend no longer works on my machine under the beta version of chrome. ie. the screen goes blank and I get errors about creating a WebGL context. We can ignore this issue for this PR and investigate it later.

The auto start functionality was removed in last PR, not this one, so it should be fix in another PR instead of this one. That issue is independent with this PR. For WebGPU issue could you share screenshot?

**Comment by peipacut** [comment]
image

and I get this in the console 
```
ParameterLabel.tsx:39 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ParameterLabel`. See https://reactjs.org/link/warning-keys for more information.
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at ParameterLabel (http://localhost:5173/src/components/ParameterComponents/ParameterLabel.tsx:29:15)
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:45929:16
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:46041:16
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:40877:16
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at SimulationColour (http://localhost:5173/src/components/ParametersBar.tsx:235:29)
    at div
    at Item3 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:53507:5)
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:53547:16
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at ParametersBar (http://localhost:5173/src/components/ParametersBar.tsx:106:45)
    at Home (http://localhost:5173/src/pages/index.tsx:41:13)
    at main
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at Xe (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:662:32)
    at App (http://localhost:5173/src/App.tsx:39:29)
printWarning @ react-jsx-dev-runtime.development.js:87
error @ react-jsx-dev-runtime.development.js:61
validateExplicitKey @ react-jsx-dev-runtime.development.js:1078
validateChildKeys @ react-jsx-dev-runtime.development.js:1105
jsxWithValidation @ react-jsx-dev-runtime.development.js:1266
ParameterLabel @ ParameterLabel.tsx:39
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less
react-dom.development.js:86 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper4 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at span
    at http://localhost:5173/node_modules/.vite/deps/chunk-EVVACM54.js?v=bd5ea2ce:1850:25
    at QuestionCircleOutlined
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:18619:24
    at DomWrapper4 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1623:5)
    at SingleObserver (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1666:24)
    at ResizeObserver3 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1743:24)
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:18639:34
    at Tooltip2 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:23562:32)
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:24184:16
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:18619:24
    at DomWrapper4 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1623:5)
    at SingleObserver (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1666:24)
    at ResizeObserver3 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:1743:24)
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:18639:34
    at Tooltip2 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:23562:32)
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:24184:16
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at div
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at ParameterLabel (http://localhost:5173/src/components/ParameterComponents/ParameterLabel.tsx:29:15)
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:45929:16
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:46041:16
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:40877:16
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at SimulationColour (http://localhost:5173/src/components/ParametersBar.tsx:235:29)
    at div
    at Item3 (http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:53507:5)
    at div
    at http://localhost:5173/node_modules/.vite/deps/antd.js?v=bd5ea2ce:53547:16
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at ParametersBar (http://localhost:5173/src/components/ParametersBar.tsx:106:45)
    at Home (http://localhost:5173/src/pages/index.tsx:41:13)
    at main
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at Xe (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:662:32)
    at App (http://localhost:5173/src/App.tsx:39:29)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
findHostInstanceWithWarning @ react-dom.development.js:28762
findDOMNode @ react-dom.development.js:29645
findDOMNode @ findDOMNode.js:17
getDom2 @ index.js:31
(anonymous) @ index.js:34
imperativeHandleEffect @ react-dom.development.js:17131
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 17 more frames
Show less
three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Web page caused context loss and was blocked
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28247
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28247
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
2three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Web page caused context loss and was blocked
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28247
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Web page caused context loss and was blocked
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28251
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28251
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
2three.module.js:28704 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Web page caused context loss and was blocked
onContextCreationError @ three.module.js:28704
getContext @ three.module.js:28207
WebGLRenderer @ three.module.js:28251
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
Show less
three.module.js:28285 THREE.WebGLRenderer: Error creating WebGL context.
WebGLRenderer @ three.module.js:28285
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less
react-dom.development.js:22839 Uncaught Error: Error creating WebGL context.
    at new WebGLRenderer (three.module.js:28257:13)
    at createRendererInstance (index-dc6125bc.esm.js:1699:69)
    at Object.configure (index-dc6125bc.esm.js:1792:18)
    at react-three-fiber.esm.js:151:20
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects (react-dom.development.js:24612:3)
    at commitRootImpl (react-dom.development.js:26823:5)
WebGLRenderer @ three.module.js:28257
createRendererInstance @ index-dc6125bc.esm.js:1699
configure @ index-dc6125bc.esm.js:1792
(anonymous) @ react-three-fiber.esm.js:151
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less
react-dom.development.js:18687 The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://localhost:5173/node_modules/.vite/deps/@react-three_fiber.js?v=bd5ea2ce:18014:3)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/@react-three_fiber.js?v=bd5ea2ce:17870:21)
    at CanvasWrapper
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at div
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at Home (http://localhost:5173/src/pages/index.tsx:41:13)
    at main
    at O2 (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:722:6)
    at Xe (http://localhost:5173/node_modules/.vite/deps/styled-components.js?v=bd5ea2ce:662:32)
    at App (http://localhost:5173/src/App.tsx:39:29)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 19 more frames
Show less
react-dom.development.js:12056 Uncaught Error: Error creating WebGL context.
    at new WebGLRenderer (three.module.js:28257:13)
    at createRendererInstance (index-dc6125bc.esm.js:1699:69)
    at Object.configure (index-dc6125bc.esm.js:1792:18)
    at react-three-fiber.esm.js:151:20
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects (react-dom.development.js:24612:3)
    at commitRootImpl (react-dom.development.js:26823:5)
```

**Comment by Lutra-Fs** [comment]
> opening the dev website with chrome beta under the command `google-chrome-unstable --enable-unsafe-webgpu --enable-features=Vulkan,UseSkiaRenderer`
> 
> 
> 
> image
> 
> 
> 
> and I get these error messages https://gist.github.com/peipacut/2eb2cb85c2c6215c49f70b9286e05bf7

Looks like it is a renderer issue, is that introduced in this PR? Can you test the main branch code?

**Comment by peipacut** [comment]
results from main branch
image

works just fine. errors are the DOMNode and unique key prop issues we've been seeing for a while.

**Review by peipacut — DISMISSED** [review]
changes look good, I'll tackle the (possibly linux related) renderer issues in a separate PR

**Comment by Lutra-Fs** [comment]
I am aware that Arc Browser with Chromium 117.0.5938.88 in Mac OS does not support WebGPU initialisation. Latest Chrome works well in Mac OS.

**Review by LorenzoValentine — APPROVED** [review]

**Pull request merged**
